### ISSUE TITLE
Cross compile problems

### ISSUE THREAD

**Issue by lrusak** [MaxKellermann/xbmc#2]
Due to your recent out of tree build fixes I am not able to build this on OpenELEC anymore without large changes to the build system. I'd rather keep this as close to upstream as possible

You can see here that we build JsonSchemaBuilder and TexturePacker for the build system as they aren't needed on the target sytem.
https://github.com/OpenELEC/OpenELEC.tv/blob/master/packages/mediacenter/kodi/package.mk#L287...#L296

Would it be possible to maintain a separate branch with just the wayland changes?

**Comment by MaxKellermann** [comment]
Need more information. "Not able to build" doesn't tell me what's going wrong.

**Comment by lrusak** [comment]
When building for the host (the build machine) we do not run ./configure in the root kodi directory, so the makefile in `tools/depends/native/JsonSchemaBuilder` is never generated, the the build fails when we try to run `make -C tools/depends/native/JsonSchemaBuilder`

I have reverted the following commits in the meantime
@937bd9a77035cb993798901d86c5ed22f1563fd2
@17e8569f568cfb7835681a60b57437520fc03bd2
@0df4c2bfa9080be134836e7eb7a28fcdc2f4d9b1

This allows me to use our normal build.

**Comment by MaxKellermann** [comment]
Sorry, I can't support a build process where you circumvent the original build scripts.

**Comment by lrusak** [comment]
I'm not asking you to. I'm simply asking if you would split your branches so I can test against the wayland implementation because I have no opinion about the build system. :)

I have no problem reverting the commits but as more commits come it becomes more to maintain that's all. I hope you are doing this work so that it will be included in upstream Kodi.

I'm trying to work with you here, I want to see wayland back in Kodi. If we work together at this it will be.
Just because you don't completely agree with Team Kodi and Team Kodi doesn't completely agree with you doesn't mean either of you are wrong. Discussion is a good thing.

**Comment by MaxKellermann** [comment]
Splitting branches is extra work for me, with exactly zero advantage for me. If were would be a permanent merge of my code (which was my initial goal), I would invest that time to make a self-contained pull request, and then never care again for that piece of code. But that's not what's happening - Team Kodi even refuses to merge my crash bug fixes, can you imagine that? So I have to maintain my fork as it is, with all those patches. When I develop a new patch, I have several build directories, all building out-of-tree, and I can build all of them within a few seconds (which is a big advantage for me). So even when developing Wayland patches, I need those out-of-tree fixes.

What you should better do is think about how you can optimize your build process to take advantage of my out-of-tree work, instead of circumventing the build scripts. Fix those problems at the cause.

**Comment by lrusak** [comment]
I think you have the wrong idea. You cannot take offence if someone criticizes your work, Team kodi wanted to discuss the reasoning for some of your changes, they are not going to just merge code that is not understood or that can be done another way.


Anyways, I'll work around your branch but if your attitude continues like this you will never see any of your work merged into upstream Kodi.

**Comment by MaxKellermann** [comment]
I did not take offense when someone criticized my work. I was annoyed because one guy kept telling me my code was wrong, but really he was wrong all the time. I was not annoyed because his "opinion" was different -- I was only annoyed because I felt he was wasting my time with his dilettantism. I have very little time for Kodi, because I have so many other projects that I feel are more important. In the little time, I want to achieve as much as I can to get my home cinema running stable. If my "attitude" means that upstream Kodi doesn't merge my work, that's fine for me.

And I disagree: individualism works. I can hack my personal Kodi fork, and anybody who wishes to use my code can just do it. Even if you think I'm an ass, you can still use my code if you believe the code is good. It's about the code, not about the people. Thanks to git, it is easy to concentrate on the code from many independent individuals. I turned down an invitation to join Team Kodi because I felt it wouldn't help me write better code -- I just want to be an individual sharing a patch every once in a while.

Don't misunderstand: if my code is not understood, I'm happy to explain. That has happend a few times with my Kodi patches. The problem is not when reviewers don't understand my code -- the real problem is when the reviewer is wrong, and refuses to listen and learn.
